# config by default
server:
  servlet:
    context-path: /nm/parking/v1
lombok:
  log:
    fieldName: log
spring:
  profiles.active: dev
---
# config for profiles dev
spring:
  config:
    activate:
      on-profile: dev
logging:
  file.name: ./logs/services-parking-dev.log
  pattern:
    console: "%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
    file: "%d{HH:mm:ss,SSS}|%50.50C:%4.4L|%-5p| %m%n"
    level:
      org.springframework: WARN
      fr.nm.parking: INFO
bordeaux:
  cub:
    url: http://data.lacub.fr/wfs?key=9Y2RU3FTE8&SERVICE=WFS&VERSION=1.1.0&REQUEST=GetFeature&TYPENAME=ST_PARK_P&SRSNAME=EPSG:4326
marseille:
  url: http://data.marseille.fr/wfs/fakeurl_dev.fr
---
# config for profiles on production
spring:
  config:
    activate:
      on-profile: prod
logging:
  file: logs/services-parking-prod.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: WARN
    fr.nm.parking: WARN
bordeaux:
  cub:
    url: http://data.lacub.fr/wfs?key=9Y2RU3FTE8&SERVICE=WFS&VERSION=1.1.0&REQUEST=GetFeature&TYPENAME=ST_PARK_P&SRSNAME=EPSG:4326
marseille:
  url: http://data.marseille.fr/wfs/fakeurl_prod.fr